### PR TITLE
[Fix #46] restore compatibility after scikit-learn's upgrade to 1.1.3

### LINKED ISSUE #46: Import error with latest sklearn version
Hi guys, this issue occured after the upgrade to 1.1.3

ImportError: cannot import name '_pprint' from 'sklearn.base'

```
/.venv/lib/python3.10/site-packages/tscv/_split.py:19 in      │
│ <module>                                                                                         │
│                                                                                                  │
│    16 import numpy as np                                                                         │
│    17 from sklearn.utils import indexable                                                        │
│    18 from sklearn.utils.validation import _num_samples, check_consistent_length                 │
│ ❱  19 from sklearn.base import _pprint                                                           │
│    20 from sklearn.utils import _safe_indexing                                                   │
│    21                                                                                            │
│    22                                       
```

Could you please fix it ?

Kind regards,
Jim

### PR DESCRIPTION
**Pull request by WenjieZ**
Fix #46

### CODE REVIEW

**Comment by WenjieZ** [comment]
Some CI failures were due to Miniconda header's errors (https://github.com/conda/conda/issues/10431)
