### ISSUE TITLE
Import error with latest sklearn version

### ISSUE THREAD

**Issue by teneon** [WenjieZ/TSCV#46]
Hi guys, this issue occured after the upgrade to 1.1.3

ImportError: cannot import name '_pprint' from 'sklearn.base'

```
/.venv/lib/python3.10/site-packages/tscv/_split.py:19 in      │
│ <module>                                                                                         │
│                                                                                                  │
│    16 import numpy as np                                                                         │
│    17 from sklearn.utils import indexable                                                        │
│    18 from sklearn.utils.validation import _num_samples, check_consistent_length                 │
│ ❱  19 from sklearn.base import _pprint                                                           │
│    20 from sklearn.utils import _safe_indexing                                                   │
│    21                                                                                            │
│    22                                       
```

Could you please fix it ?

Kind regards,
Jim

**Comment by teneon** [comment]
It seems like sklearn moved _pprint to a different place in latest 1.3 version:

# from sklearn.base import _pprint (doesn't exist anymore)
from sklearn.utils import _pprint (seems to be the new location?)

Best regards,
Jim

**Comment by WenjieZ** [comment]
Hi, @teneon, thank you for bringing this to my attention. 

The function `_pprint` desired has been moved to `sklearn.model_selection`. The solution would be either I import from there or I write my version of `_pprint`.

**Comment by WenjieZ** [comment]
I have released the latest version `v0.1.3` on PyPI. Have a try and let me know whether this solves your problem @teneon.
